name = "BiotBrinkmanWithVorticityPaper"
uuid = "83f6fa47-a338-4b6a-92e4-92fcc44a4bf6"
authors = ["Ruben Caraballo-Diaz <ruben.caraballo@alumnos.ubiobio.cl>", "Chansophea Wathanak In <cwin18@student.monash.edu>", "Alberto F. Martin <alberto.f.martin@anu.edu.au>", "Ricardo Ruiz-Baier <ricardo.ruizbaier@monash.edu>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.9"
DataFrames = "1.5.0" 
DrWatson = "2.12.5" 
Gridap = "0.17.17" 
Krylov = "0.9.1"
KrylovKit = "0.6.0" 
LaTeXStrings = "1.3.0" 
LinearOperators = "2.5.2" 
Pluto = "0.19.26"     
PlutoUI = "0.7.51" 

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
